### ISSUE TITLE
add a link to the published mbed os docs in the github project description

### ISSUE THREAD

**Issue by jrobeson** [ARMmbed/GettingStartedmbedOS#13]
It'd be nice if there was link to the published docs in the github project description.

**Comment by 0xc0170** [comment]
PR welcome!

**Comment by jrobeson** [comment]
it's in the Github project settings, thus only project admins can add it. I didn't mean the README.

**Comment by jrobeson** [comment]
Example: https://github.com/rust-lang/rust  See where it says:  "A safe, concurrent, practical language. http://www.rust-lang.org"

**Comment by 0xc0170** [comment]
I see, the project description.

@iriark01 shall we add more meaningful description ?

**Comment by iriark01** [comment]
Thanks
